service: star-wars-api

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev
  environment:
    DYNAMODB_TABLE: 'Peoples'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
  - serverless-webpack
build:
  esbuild: false
