service: star-wars-api

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  stage: dev
  environment:
    DYNAMODB_TABLE: 'Peoples'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}

functions:
  app:
    handler: dist/bundle.handler
    events:
      - http:
          path: api
          method: ANY

plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true
  exclude:
    - node_modules/**
    - src/**
    - tests/**
    - webpack.config.js

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

build:
  esbuild: false
