service: swapi-serverless

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: dev

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: api/docs
          method: get
      - http:
          path: api/docs/json
          method: get
      - http:
          path: api/swapi/people
          method: get
      - http:
          path: api/swapi/people
          method: post
      - http:
          path: api/swapi/people/{id}
          method: get

plugins:
  - serverless-offline

package:
  individually: true